RGB_LIB_DISTRIBUTION=rpi-rgb-led-matrix
RGB_INCDIR=$(RGB_LIB_DISTRIBUTION)/include
RGB_LIBDIR=$(RGB_LIB_DISTRIBUTION)/lib
RGB_LIBRARY_NAME=rgbmatrix
RGB_LIBRARY=$(RGB_LIBDIR)/lib$(RGB_LIBRARY_NAME).a
RGB_LDFLAGS+=-L$(RGB_LIBDIR) -l$(RGB_LIBRARY_NAME) -lrt -lm -lpthread

class.sources = ltbl.c
cflags = -I$(RGB_INCDIR)
ldflags = $(RGB_LDFLAGS) -lstdc++

PDINCLUDEDIR = pdinclude
PDLIBDIR = $(HOME)/.local/lib/pd/extra-purr-data  # make installs here

include pd-lib-builder/Makefile.pdlibbuilder
